version: '3.8'

services:
  postgres:
    image: postgres:15
    env_file:
      - ./app/.env
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    ports:
      - "5432:5432"

  app:
    build: ./app
    env_file:
      - ./app/.env
    depends_on:
      - postgres
    ports:
      - "8000:8000"

  prometheus:
    image: prom/prometheus
    volumes:
      - ./prometheus.yml:/etc/prometheus/prometheus.yml
    ports:
      - "9090:9090"

  grafana:
    image: grafana/grafana-enterprise
    volumes:
      - grafana_data:/var/lib/grafana
    depends_on:
      - postgres
    ports:
      - "3000:3000"

volumes:
  postgres_data:
  grafana_data: